---
title: "{{{name}}}"
format: dashboard
params:
  name: "{{{name}}}"
---

```{r}
#| label: params
#| eval: !expr interactive()
#| include: false
params = list(name = "{{{name}}}")
```

```{r}
#| label: setup
#| message: false
#| include: false
#| warning: false
wd <- "{{{path_proj}}}"
if (basename(getwd()) != wd) {
  setwd(here::here(wd))
}
here::i_am(paste0(params$name, ".qmd"), uuid = "{{{uuid}}}")
projthis::proj_create_dir_target(params$name, clean = FALSE)
path_target <- projthis::proj_path_target(params$name)
path_source <- projthis::proj_path_source(params$name)
path_raw <- path_source("00-raw")
path_resource <- here::here(path_raw, "d00-resource")
path_data <- here::here(path_raw, paste0("d", params$name))
dir.create(path_raw, recursive = TRUE, showWarnings = FALSE)
dir.create(path_data, recursive = TRUE, showWarnings = FALSE)
dir.create(path_resource, recursive = TRUE, showWarnings = FALSE)
```

```{r}
#| label: packages
#| message: false
suppressPackageStartupMessages({
  library(here)
  library(conflicted)
  library(tidyverse)
  library(data.table)
  devtools::load_all()
})
```


```{r}
#| label: list-files-target
#| include: false
projthis::proj_dir_info(path_target(), tz = "CET")
```