---
title: "{{{name}}}"
title-block-banner: true
author:
  - name: Jinlong Ru
    orcid: 0000-0002-6757-6018
date: 2024-01-06
toc: true
toc-depth: 4
number-sections: true
code-fold: true
code-line-numbers: true
code-tools: true
format: 
  html:
    embed-resources: true
    smooth-scroll: true
    page-layout: article
reference-location: section
citation-location: document
params:
  name: "{{{name}}}"
---

**Updated: `r format(Sys.time(), '%Y-%m-%d %H:%M:%S', tz = 'CET')` CET.**

The purpose of this document is ...

```{r setup}
#| message: false
#| include: false
here::i_am(paste0(params$name, ".qmd"), uuid = "{{{uuid}}}")
projthis::proj_create_dir_target(params$name, clean = FALSE)
path_target <- projthis::proj_path_target(params$name)
path_source <- projthis::proj_path_source(params$name)
path_raw <- path_source("00-raw")
dir.create(path_raw, recursive = T)
path_data <- here::here(path_raw, paste0("d", params$name))
dir.create(path_data, recursive = T)
```

```{r packages}
#| message: false
suppressPackageStartupMessages({
    library(here)
    library(conflicted)
    library(tidyverse)
})
```

## Tasks

The first task is ...

## Files written

These files have been written to the target directory, ```r paste0("data/", params$name)```:

```{r list-files-target}
projthis::proj_dir_info(path_target(), tz = "CET")
```

