#' Create project
#'
#' @description
#' Creates a new analysis project directory with a `DESCRIPTION` file,
#' `NAMESPACE`, `README.md`, and `.gitignore`.
#'
#' Provide an absolute `path`, or a relative `path` from your current
#' working-directory.
#'
#' @param path `character` path to the new project directory.
#' @param fields `list` of additional fields to set in `DESCRIPTION`.
#'
#' @return Invisible `character` path to the created project, called for
#'   side effects.
#' @examples
#' # not run because it produces side effects
#' if (FALSE) {
#'   proj_create("../new-project-name")
#' }
#' @export
#'
proj_create <- function(path, fields = list()) {

  # Create project directory
  fs::dir_create(path)

  # Set up DESCRIPTION using desc package
  desc::desc_new(
    Package = basename(path),
    Title = "Analysis Project",
    Version = "0.1.0",
    file = fs::path(path, "DESCRIPTION")
  )

  # Create NAMESPACE
  writeLines("# Generated by roxygen2: do not edit by hand", fs::path(path, "NAMESPACE"))

  # Create README.md
  writeLines(c(
    paste0("# ", basename(path)),
    "",
    "An analysis project."
  ), fs::path(path, "README.md"))

  # Create .gitignore
  writeLines(c(".Rproj.user", ".Rhistory", ".RData", ".Ruserdata"), fs::path(path, ".gitignore"))

  cli::cli_alert_success("Created project at {.path {path}}")
  cli::cli_alert_info("Next: call {.fn proj_use_workflow} to set up an analyses directory.")

  invisible(path)
}

#' Set up workflow directory
#'
#' @description
#' Creates an `analyses/` directory (or custom path) with a `data/`
#' subdirectory, `.gitignore` rules, and a `README.md`.
#'
#' @param path_proj `character` path to the workflow directory,
#'   relative to the project directory. Defaults to `"analyses"`.
#' @param git_ignore_data `logical` indicates to add `data` directory
#'   contents to `.gitignore`.
#'
#' @return Invisible `NULL`, called for side effects.
#' @examples
#' # not run because it creates side effects
#' \dontrun{
#'   proj_use_workflow()
#' }
#' @export
#'
proj_use_workflow <- function(path_proj = "analyses", git_ignore_data = TRUE) {

  # Create the analyses directory
  fs::dir_create(path_proj)

  # Create data subdirectory
  data_dir <- fs::path(path_proj, "data")
  fs::dir_create(data_dir)

  # Create data/README.md so git tracks the folder
  data_readme <- fs::path(data_dir, "README.md")
  if (!fs::file_exists(data_readme)) {
    writeLines(c("# Data Directory", "", "Data files in this folder are ignored by git."), data_readme)
  }

  # Write .gitignore rules
  if (git_ignore_data) {
    gitignore_path <- ".gitignore"
    ignores <- c(
      paste0(path_proj, "/data/*"),
      paste0(path_proj, "/tmp/"),
      paste0("!", path_proj, "/data/README.md")
    )
    # Append only new lines
    existing <- if (fs::file_exists(gitignore_path)) readLines(gitignore_path) else character(0)
    new_lines <- ignores[!ignores %in% existing]
    if (length(new_lines) > 0) {
      write(new_lines, gitignore_path, append = TRUE)
    }
  }

  # Create analyses/README.md
  readme_path <- fs::path(path_proj, "README.md")
  if (!fs::file_exists(readme_path)) {
    writeLines(c(
      paste0("# ", basename(path_proj)),
      "",
      "This directory contains the analysis workflow.",
      "",
      "## Structure",
      "",
      "- Each analysis file writes only to its own subdirectory of `data/`.",
      "- Files are named with a numeric prefix to indicate execution order,",
      "  e.g. `00-import.qmd`, `01-clean.qmd`, `99-summary.qmd`.",
      "",
      "## Usage",
      "",
      "Create a new analysis file:",
      "",
      "```r",
      'qproj::use_qmd("01-clean")',
      "```"
    ), readme_path)
  }

  cli::cli_alert_success("Created workflow directory at {.path {path_proj}}")
  cli::cli_alert_info("Create analysis files with {.fn use_qmd}, e.g. {.code use_qmd(\"01-import\")}")

  invisible(NULL)
}
